# Business Category ID according to https://share.philips.com/sites/SWCoE/Lists/List%20of%20Business%20Categories/AllItems.aspx
# Example for SWCoE: 62
business-category: 56

# Direct link to details business-category. Change the ID in the URL below.
business-category-details: https://share.philips.com/sites/SWCoE/Lists/List%20of%20Business%20Categories/DispForm.aspx?ID=56